version: '3.7'
# networks:
#   proxy_https_default:
#      external: true
services:
  nginx:
    build: ./nginx
    ports:
      - 1400:80
    # environment:
    #   - VIRTUAL_HOST=${DOMAIN}
    #   - VIRTUAL_PORT=80
    #   - LETSENCRYPT_HOST=${DOMAIN}
    #   - LETSENCRYPT_EMAIL=dev.harouna@gmail.com
    volumes:
      - static_volume:/app/static
    depends_on:
      - web
    restart: "on-failure"
    # networks:
    #   - default
    #   - proxy_https_default
  web:
    build: . #build the image for the web service from the dockerfile in parent directory
    command: sh -c "gunicorn app:app --bind 0.0.0.0:${APP_PORT}"
    volumes:
      - .:/app:rw # map data and files from parent directory in host to microservice directory in docker containe
      - static_volume:/app/static
    env_file:
      - .env
    image: comming_soom

    expose:
      - "${APP_PORT}"
    restart: "on-failure"

volumes:
  static_volume:
    